config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'pages#home'
  #get 'dashboard', to: 'pages#dashboard '

  resources :boats do
    resources :orders, only: [:index, :new, :create]
  end
  resources :orders, only: [:edit, :show, :destroy, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :orders

  has_many_attached :photos
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :boat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boats
  has_many :orders

  # mount_uploader :photo, PhotoUploader

  # before_create :photo_or_default

  # def photo_or_default
  #   @photo = photo.file.nil? ? "" : photo
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
  @boats = Boat.all
 end

  def new
   @boat = Boat.new
 end

  def show
    @boat = Boat.find(params[:id])
  end

  def create
    @boat = Boat.new(boat_params)
    @user = User.first
    @boat.user = @user
    if @boat.save
      redirect_to boats_path
    else
      render :new
    end
  end

  private

  def set_boat
    @boat = Boat.find(params[:id])
  end

  def boat_params
    params.require(:boat).permit(:name, :description, :price, photos:[])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
    @boats = Boat.all.where(user_id: current_user)
  end

  def new
    @boat = Boat.find(params[:boat_id])
    @order = Order.new
  end

  def create
    @user = User.first
    @boat = Boat.find(params[:boat_id])
    @order = Order.new(order_params)
    @order.user = @user
    @order.boat = @boat
    if @order.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:start_date, :end_date, :boat_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/index.html.erb
<div class= "container">
  <div class="my-4">
   <h1 style="text-align:center"> Rent any kind of boats </h1>
  </div>

  <div class="cards">
    <% @boats.each do |boat| %>
        <%= link_to boat_path(boat) do %>
        <div>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),  url('<%= cl_image_path boat.photos.first.key, crop: :fill %>')">
              <%= boat.name %>
          </div>
          <div class= "d-flex justify-content-around">
            <p> <%= boat.description %> </p>
            <p> <%= boat.price %> Dhs/Day </p>
          </div>
        </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/boats/new.html.erb
<div class="container py-5">
  <div class="form-group">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3> Book Form </h3>
        <%= simple_form_for (@boat) do |f| %>
          <%= f.input :name   %>
          <%= f.input :description %>
          <%= f.number_field :price %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit id: "button-create"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boats/show.html.erb
<div class="container un">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" style="width:80%; height:500px; margin:auto">
      <div class="carousel-item active">
        <img src="https://scontent.fcmn3-1.fna.fbcdn.net/v/t1.6435-9/251382640_10158532599447399_5018250399661044598_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=973b4a&_nc_ohc=Z0-4pfPXvrwAX_zQdXr&_nc_ht=scontent.fcmn3-1.fna&oh=abe72a3a02f7326cbe0927230828d082&oe=61A798E7" class="d-block w-100" alt="bateau1">
        <div class="carousel-caption d-none d-md-block">
          <h5><strong>A fantastic Journey</strong></h5>
          <p>A unique experience on an unique boat</p>
        </div>
    </div>
    <div class="carousel-item">
      <img src="https://scontent.fcmn3-2.fna.fbcdn.net/v/t1.6435-9/251680364_10158532599442399_6403757992354938250_n.jpg?_nc_cat=106&ccb=1-5&_nc_sid=973b4a&_nc_ohc=JjQLxjkZ4I0AX9D6sCp&_nc_ht=scontent.fcmn3-2.fna&oh=0e6ca09525288ebf46a61800a15e8a76&oe=61AB17A0" class="d-block w-100" alt="bateau2">
      <div class="carousel-caption d-none d-md-block">
        <h5><strong>Discover the unknown</strong></h5>
        <p>Lose yourself into this mesmerising blue color.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://scontent.fcmn3-1.fna.fbcdn.net/v/t1.6435-9/251382640_10158532599447399_5018250399661044598_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=973b4a&_nc_ohc=Z0-4pfPXvrwAX_zQdXr&_nc_ht=scontent.fcmn3-1.fna&oh=abe72a3a02f7326cbe0927230828d082&oe=61A798E7" class="d-block w-100" alt="bateau3">
      <div class="carousel-caption d-none d-md-block">
        <h5><strong>Ocean life with the higher existing standarts </strong></h5>
        <p>Enjoy your journey with a maximal comfort and a dedicated team !</p>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<div class="productView">
  <div class="card">
    <div class="card">
      <div class="card-header">
        <h2>Angela</h2>
      </div>
      <h2 class="card-trip-pricing">1599,99 Dhs</h2>
      <div class="card-body">
      <div class="card-product-infos">
        <h2>Description</h2>
        <p>SPECIFICATIONS Number of crew: 4 Flag: Maltese
          Air conditioning, Stabilisers at anchor, Stabilisers underway, WiFi connection on board

          EQUIPMENT
          Cruising speed: 21
          Fuel consumption: 600 Litres/Hr

          ACCOMMODATION
          Cabin configuration: 4 Double, 1 Convertible
          Bed configuration: 1 Pullman, 4 Queen, 1 Double, 2 Single, 1 Convertible

          WATER SPORTS
          Tenders + toys: Tender : Williams 445
          Jetski : SEADOO RXP 300
          Jetski : YAMAHA SUPERJET <strong>Prestige</strong> only.</p>
      </div>
    </div>

    <div class="btn btn-flat">
     <%= link_to "Book Now", new_boat_order_path(@boat)%>
    </div>

  </div>
</div >

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MOULBATORailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/orders/index.html.erb
 <% @orders.each do |order| %>
    <li><%= order.name  hello %></li>
  <% end %>
</ul>

app/views/orders/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3> Book a Boat </h3>

        <%= simple_form_for [@boat, @order] do |f| %>
          <%= f.input :start_date, as: :date %>
          <%= f.input :end_date, as: :date %>
          <%= f.submit "Submit", class: "btn btn-primary"  %>
          <% end %>
      </div>
     </div>
  </div>
</div>